language: node_js

node_js:
   - node # will use latest node

cache: yarn

before_script: cd frontEnd && yarn

script: # the build step
   - yarn run build

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

deploy:
  local-dir: frontEnd/dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master