language: node_js
node_js:
- node
cache: yarn
script:
- yarn run build
notifications:
  email:
    on_failure: change
    on_success: change

addons:
  ssh_known_hosts: ec2-52-23-192-142.compute-1.amazonaws.com

before_deploy:
- openssl aes-256-cbc -K $encrypted_2cd42bf4aa47_key -iv $encrypted_2cd42bf4aa47_iv -in angular_attack-cert.enc -out angular_attack-cert -d
- eval "$(ssh-agent -s)"
- chmod 600 angular_attack-cert
- ssh-add angular_attack-cert

deploy:
  - provider: pages
    local-dir: dist
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh ubuntu@ec2-52-23-192-142.compute-1.amazonaws.com "cd angularattack2018-toolshed/backend && git pull && /usr/bin/pm2 restart angular-attack"
    on:
      branch: master

