version: '2.2'
services:
  db:
    image: postgres:10.3-alpine
    expose:
      - "5432"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: postgres
